Repository ryodeushii/gem80-qmk-firmware, pull requests merged in 2024-04, with the labels that each got.

#4 add MacOS globe key
  keyboards/nuphy/gem80/ansi/ansi.c
  keyboards/nuphy/gem80/ansi/ansi.h
  keyboards/nuphy/gem80/ansi/keymaps/via/NuPhy Gem80 via3.json
Labels: size/S

#6 chore: update readme
  keyboards/nuphy/gem80/ansi/readme.md
Labels: size/XS

#7 chore: cleanup, move some values from config.h and rules.mk to info.json
  keyboards/nuphy/gem80/ansi/config.h
  keyboards/nuphy/gem80/ansi/info.json
  keyboards/nuphy/gem80/ansi/rules.mk
Labels: size/S

#8 chore: rename _user methods to _kb, rename some stuff
  keyboards/nuphy/gem80/ansi/ansi.c
  keyboards/nuphy/gem80/ansi/side.c
  keyboards/nuphy/gem80/ansi/side_driver.c
  keyboards/nuphy/gem80/ansi/side_logo.c
  keyboards/nuphy/gem80/ansi/user_kb.c
Labels: size/S

#9 chore: move LTO optimizations to keymap rules.mk
  keyboards/nuphy/gem80/ansi/keymaps/via/rules.mk
  keyboards/nuphy/gem80/ansi/rules.mk
Labels: size/XS

#10 chore: cleanup unused vars
  keyboards/nuphy/gem80/ansi/ansi.c
  keyboards/nuphy/gem80/ansi/user_kb.c
Labels: size/XS

#11 chore: cleanup sym_eager_pk debounce in favor of current asym_eager_defer
  keyboards/nuphy/gem80/ansi/config.h
  keyboards/nuphy/gem80/ansi/debounce.c
  keyboards/nuphy/gem80/ansi/mods.md
Labels: size/L

#12 feat: add white NUM_LOCK indicator on Logo LED
  keyboards/nuphy/gem80/ansi/side.c
Labels: size/S
